### ISSUE TITLE
Do you have a plan to release SBPL on ROS Kinetic version?

### ISSUE THREAD

**Issue by robotpilot** [ros-gbp/sbpl-release#2]
Hello, Michael Ferguson,

I am Yoonseok Pyo in ROBOTIS.

I have a plan to release the Thormang3 packages (kinetic version, http://wiki.ros.org/ROBOTIS-THORMANG3). But the SBPL package is not on Kinetic yet, I saw related wiki (http://wiki.ros.org/sbpl). The SBPL package maintained by you is very important for us. 

Do you have a plan to release SBPL on ROS Kinetic version?

**Comment by AravindaDP** [comment]
Any update on this?

**Comment by robotpilot** [comment]
@dirk-thomas @tfoote 
Do you have any plan to release **SBPL** on ROS **Kinetic** or **Molodic** version?
I think this package will be very useful for **humanoid** robots using **ROS**.

**Comment by tfoote** [comment]
This is not a package that we will have time to maintain from Open Robotics.

**Comment by mikeferguson** [comment]
Similarly, I'm maintaining a slightly smaller set of packages these days. While I released this into indigo, I have no intentions of doing further releases at this time.

If someone wants to step forward and handle releases, that'd be great. Releasing the existing version should be pretty straight forward, I imagine some folks would like to see the newer releases make it into ROS.

**Comment by robotpilot** [comment]
@tfoote Thank you. I understand. I also think community members should share their work.

@mikeferguson Hi, Thank you for your reply. Can I take charge of the release? Keep the current release repository? or Change it?

**Comment by robotpilot** [comment]
FYI, https://github.com/ros/rosdistro/pull/17302
Thanks, :)
